---
docker_dependencies:
  - apt-transport-https
  - ca-certificates
  - lsb-release
  - gnupg

docker_packages:
  - docker
  - docker.io
  - docker-compose
  - docker-registry

docker_key_url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"

docker_repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
