---
- name: Install apt-transport-https
  apt:
    name: "{{ docker_dependencies }}"
    state: present

- name: Add signing key
  apt_key:
    url: "{{ docker_key_url }}"
    state: present

- name: Add repository into sources list
  apt_repository:
    repo: "{{ docker_repo }}"
    state: present
    filename: docker

- name: Install Docker
  apt:
    name: "{{ docker_packages }}"
    state: present
    update_cache: true

- name: Start Docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
