---
- name: Install apt-transport-https
  ansible.builtin.apt:
    name: "{{ docker_dependencies }}"
    state: present

- name: Add signing key
  ansible.builtin.apt_key:
    url: "{{ docker_key_url }}"
    state: present

- name: Add repository into sources list
  ansible.builtin.apt_repository:
    repo: "{{ docker_repo }}"
    state: present
    filename: docker

- name: Install Docker
  ansible.builtin.apt:
    name: "{{ docker_packages }}"
    state: present
    update_cache: true

- name: Start Docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
