---
- name: "Create {{ new_group }} group"
  ansible.builtin.group:
    name: "{{ new_group }}"
    state: present

- name: Add new user
  ansible.builtin.user:
    name: "{{ new_user }}"
    group: "{{ new_group }}"
    shell: /bin/bash

- name: Install zsh and curl
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
