---
- name: "Create {{ new_group }} group"
  group:
    name: "{{ new_group }}"
    state: present

- name: Add new user
  user:
    name: "{{ new_user }}"
    group: "{{ new_group }}"
    shell: /bin/bash

- name: Install zsh and curl
  package:
    name: "{{ packages }}"
    state: present
    update_cache: true
