---
- name: Install Nginx
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Update Cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present
      register: nginx_install

    - name: Print Nginx Install
      ansible.builtin.debug:
        var: nginx_install

    - name: Start Nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

    - name: Copy index.html
      ansible.builtin.copy:
        src: files/index.html
        dest: /var/www/html/index.html
        mode: 0644

    - name: Restart Nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded

    - name: Install pip3
      ansible.builtin.apt:
        name: python3-pip
        state: present

    - name: Pip install docker
      ansible.builtin.pip:
        name: docker
        state: present
        executable: pip3

    - name: Install Docker
      ansible.builtin.apt:
        name: docker.io
        state: present

    - name: Enable Docker
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes
