---

- name: Install required software on instances
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Update Cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install wget
      ansible.builtin.apt:
        name: wget
        state: present

    - name: Install unzip on the first instance
      ansible.builtin.apt:
        name: unzip
        state: present
      when: "'instance1' in inventory_hostname"

    - name: Install nginx on the second instance
      ansible.builtin.apt:
        name: nginx
        state: present
      when: "'instance2' in inventory_hostname"

    # Stretch Goal

    - name: Uninstall Unzip
      ansible.builtin.apt:
        name: unzip
        state: absent
