---

- name: Install Nginx
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Update Cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: Start Nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

    # Stretch Goal

    - name: Install Unzip
      ansible.builtin.apt:
        name: unzip
        state: present
