---
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: true

- name: Start Nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: Replace default HTML with custom HTML
  copy:
    src: files/index.html
    dest: /var/www/html/index.nginx-debian.html
  notify: restart nginx
