---
- name: Ensure dependencies are installed.
  ansible.builtin.apt:
    name: openjdk-11-jdk
    state: present
    update_cache: true

- name: Add Jenkins apt repository key.
  ansible.builtin.apt_key:
    url: "{{ jenkins_repo_key_url }}"
    state: present

- name: Add Jenkins apt repository.
  ansible.builtin.apt_repository:
    repo: "{{ jenkins_repo_url }}"
    state: present

- name: Ensure Jenkins is installed.
  ansible.builtin.apt:
    name: jenkins
    state: present
    update_cache: true

- name: Ensure Jenkins is running.
  ansible.builtin.service:
    name: jenkins
    state: started
    enabled: true

- name: Wait for Jenkins to start.
  ansible.builtin.wait_for:
    port: 8080
    timeout: 60

- name: Ensure Jenkins is accessible.
  ansible.builtin.uri:
    url: "http://{{ ansible_host }}:8080/login?from=%2F"
    status_code: 200
    timeout: 5

- name: Get Jenkins initial admin password.
  ansible.builtin.command: "cat /var/lib/jenkins/secrets/initialAdminPassword"
  changed_when: false
  register: jenkins_initial_admin_password

- name: Print Jenkins initial admin password.
  ansible.builtin.debug:
    msg: "Jenkins initial admin password is {{ jenkins_initial_admin_password.stdout }}"
