---

- name: Update apt cache if needed.
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Start Nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Copy index.html
  ansible.builtin.copy:
    src: files/index.html
    dest: /var/www/html/index.nginx-debian.html
    mode: 0644

- name: Reload Nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
