---
- name: Lab 4 Playbook
  hosts: all
  become: yes
  gather_facts: no
  vars_files:
    - vars.yml

  vars_prompt:
    - name: "package_var"
      prompt: "What package do you want to install?"
      private: no
    - name: "text_to_append"
      prompt: "What text do you want to append to a file?"
      private: no

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Print name
      ansible.builtin.debug:
        msg: "My name is {{ my_name }}"

    - name: Clone down a repo
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ home }}/{{ repo_name }}"

    - name: Install specified package
      ansible.builtin.apt:
        name: "{{ package_var | default('unzip', true) }}"
        state: present

    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
        state: present
      notify: restart nginx

    - name: Create a new file
      ansible.builtin.file:
        path: "{{ home }}/test.txt"
        state: touch
        mode: 0644

    - name: Append text to file
      ansible.builtin.lineinfile:
        path: "{{ home }}/test.txt"
        line: "{{ text_to_append }}"

  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
