---

- name: Lab 4 Playbook
  hosts: all
  become: yes
  gather_facts: no

  vars_prompt:
    - name: "package_var"
      prompt: "What package do you want to install?"
      private: no
    - name: "text_to_append"
      prompt: "What text do you want to append to a file?"
      private: no

  tasks:
    - include_vars: vars.yml

    - name: Update apt cache
      apt: update_cache=yes cache_valid_time=3600

    - name: Print name
      debug:
        msg: "My name is {{ my_name }}"

    - name: Clone down a repo
      git:
        repo: "{{ repo_url }}"
        dest: "{{ home }}/{{ repo_name }}"

    - name: Install specified package
      apt:
        name: "{{ package_var | default('unzip', true) }}"
        state: present

    - name: Install nginx
      apt:
        name: nginx
        state: present
      notify: restart nginx

    - name: Create a new file and append text
      file:
        path: "{{ home }}/test.txt"
        state: touch
    - lineinfile:
        path: "{{ home }}/test.txt"
        line: "{{ text_to_append }}"

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: reloaded
