---

- name: Example Playbook
  hosts: all
  become: yes
  gather_facts: no

  include_vars: vars.yml

  tasks:
    - name: Print name
      debug:
        msg: "My name is {{ my_name }}"
      vars:
        my_name: "Brad"
  
    - name: Clone down a repo
      git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_url.split('/')[-1].split('.')[0] }}"
  
    - name: Install specified package
      apt:
        name: "{{ package_var | default('unzip') }}"
        state: present
  
    - name: Install nginx
      apt:
        name: nginx
        state: present
      notify: restart nginx
  
    - name: Create a new file and append text
      file:
        path: "/usr/share/nginx/html/index.html"
        state: touch
      lineinfile:
        path: "/usr/share/nginx/html/index.html"
        line: "{{ text_to_append }}"
  
  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
