---

- name: Lab 4 Playbook
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - include_vars: vars.yml

    - name: Print name
      debug:
        msg: "My name is {{ my_name }}"

    - name: Clone down a repo
      git:
        repo: "{{ repo_url }}"
        dest: "{{ home }}/{{ repo_name }}"

    - name: Install specified package
      apt:
        name: "{{ package_var | default('unzip') }}"
        state: present

    - name: Install nginx
      apt:
        name: nginx
        state: present
      notify: restart nginx

    - name: Create a new file and append text
      file:
        path: "{{ home }}/test.txt"
        state: touch
    - lineinfile:
        path: "{{ home }}/test.txt"
        line: "{{ text_to_append }}"

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: reloaded
